/* confdefs.h */
#define PACKAGE_NAME "L15 Core"
#define PACKAGE_TARNAME "l15-core"
#define PACKAGE_VERSION "0.0.dev"
#define PACKAGE_STRING "L15 Core 0.0.dev"
#define PACKAGE_BUGREPORT "l2xl@protonmail.com"
#define PACKAGE_URL ""
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define PACKAGE "l15-core"
#define VERSION "0.0.dev"
#define HAVE_CXX20 1
#define HAVE_BOOST /**/
#define HAVE_BOOST_FILESYSTEM /**/
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD 1
#define HAVE_ZMQ 1
#define HAVE_DUP2 1
#define HAVE_MEMSET 1
#define HAVE_STRTOUL 1
#define HAVE_STRTOULL 1
